[ui]
# Hide the main menu 
hideTopBar = true

[theme]
# Custom theme settings
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
